config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users
  

	  resources :posts do
	  	resources :comments
	  	resources :likes
      collection do
        get :recent
        get :tagged_with
      end
	  end


  resources :categories
  resources :users, only: [:show, :edit, :update] do
    resources :locations
  end
  get '/users/:user_id/locations/:id/sua_diadiem' => 'locations#sua_diadiem', as: :sua_diadiem
  get 'community', to: "users#community", as: :community
  
  get 'welcome/index'
  root 'welcome#index'

  get '/tagged', to: "posts#tagged", as: :tagged

  get '/search' => 'posts#search', :as => 'search_page'

#test
  get '/tag', to: "posts#click_tag", as: :tag


  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_rich_text :body
  has_one_attached :image
  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  #has_many :locations, dependent: :destroy


  scope :last_n_days, ->(days) {where('created_at > ?', days)}
  scope :last_5_days, ->{order('created_at DESC')}
  scope :last_1_year, -> {where(created_at: (Time.now.midnight - 365.day)..Time.now.midnight)}

#geocode
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  validates_presence_of :address


  #tam test chua dung dc
  scope :including_all_tags, -> (tags) { where(matching_tag_query(tags, 'AND')) }

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :interests, :types, :away, :monan

  $interests = ['spacious', 'delicious', 'affordable', 'childrend friendly', 'car park', 'nice service'] 
  $types = ['Tea & coffee', 'Restaurant', 'Wine & bar', 'Fast food', 'Cake']
  $away = ['not_be_back', 'Overpriced', 'rude', 'slow']
  $monan = ['Sea food', 'hot pot', 'pho', 'steak pizza rib', 'vegan', 'Meat and Poultry']


  after_commit :create_hash_tags, on: [:create]
  after_commit :update_hash_tags, on: [:update]
  after_create_commit :add_image_to_posts


  def update_hash_tags
  	hash_tags.destroy_all
	  extract_name_hash_tags.each do |name|
	    hash_tags.create(name: name)
	  end
	end

  def create_hash_tags
	  extract_name_hash_tags.each do |name|
	    hash_tags.create(name: name)
	  end
	end
  def extract_name_hash_tags
	  content.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
	end

  def add_image_to_posts
    if !image_url.present?
      update!(image_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80")
    end
  end
  # test search pg
  #def self.search(search)
  #  where("title LIKE ?", "%#{search}%") 
  #  where("content LIKE ?", "%#{search}%")
  #end

  def self.recently(recently)
    Post.last_n_days(Time.now + 1 - recently.to_i.days)
  end
  
  include PgSearch::Model
    pg_search_scope :search_by_title, against: [:title, :content],
                    associated_against: {
                                          types: [:name],
                                          interests: [:name],
                                          tags: [:name]
                                        }
  
  def matching_tag_query(tags, condition_separator = 'OR')
    tags.map { |tag| "(posts.category_id LIKE '%#{tag}%')" }.join(" #{condition_separator} ")
  end

  def self.search(search)  
     where("lower(posts.title) LIKE :search OR lower(categories.name) LIKE :search", search: "%#{search.downcase}%").uniq   
  end                                    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create]


  # GET /posts
  # GET /posts.json
  def index
    @comment = Comment.new
 
    @top5posts = Post.order('title DESC').limit(5)
    @all_posts = Post.all

    
    if current_user && current_user.locations.any?
      @post = current_user.posts.build
      @lat = current_user.locations.last.latitude
      @long = current_user.locations.last.longitude

      @nearby_post = Post.near([@lat, @long], 5)
      #@nearby_post = Post.near([20.98, 105.81], 50)

    
    if @post.save 
      redirect_to @post, notice: 'Post was successfully created.'
      #format.json { render :show, status: :created, location: @post }
    end

    end

    handle_search_name
    handle_filters
    
    respond_to do |format|
        format.html
        format.js
    end

    @tags = ["cơm", "cafe", "pizza"]
  end

  def click_tag
    #thu test category
    @tags = ["cơm", "cafe", "pizza"]
    if params[:basic]
      @posts = Post.where("posts.title LIKE :search OR posts.content LIKE :search", search: "%#{params[:basic]}%")
      .order("created_at DESC") 
      flash[:notice] = "There are <b>#{@posts.count}</b> in this category".html_safe
      
    else
      @posts = Post.all
    end
    render 'index'

    #still worked
    #if params[:basic]
    #  @posts = Post.where("title LIKE ? OR content LIKE ?", "%" + params[:basic] + "%", "%" + params[:basic] + "%") 
    #  flash[:notice] = "There are <b>#{@posts.count}</b> in this category".html_safe
    #  
    #else
    #  @posts = Post.all
    #end

  end

  def recent
    @posts = Post.last_5_days
    render action: :index
  end

  def tagged_with
    if params[:post_tag].present?
      @posts = Post.tagged_with(params[:post_tag])
    end 
      render action: :index
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new

    pre_like = @post.likes.find { |like| like.user_id == current_user.id}
    if pre_like
      @like = current_user.likes.find_by(post_id: @post.id)
    else
      @like = current_user.likes.new(post_id: @post.id)
    end

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end

  def tagged
  if params[:tag].present?
    @posts = Post.tagged_with(params[:tag])
  else
    @posts = Post.all
  end
end

  private
    def handle_search_name
      if params[:pg_search]
        @posts = Post.search_by_title(params[:pg_search])
        #@count = @posts.count
      else
        @posts = Post.all 
        #@posts = Post.paginate(:page => params[:page], :per_page => 20)
        #redirect_to root_path if @posts.empty?
      end
    end
    

        #test search
    def handle_filters    
      #if params[:category]
      #  @posts = Post.where("posts.category_id IN (?)", params[:category]) 
        if params[:filter]
          @filter = params["filter"]["types"].concat(params["filter"]["interests"]).flatten.reject(&:blank?)
          @posts = @filter.empty? ? @posts : Post.all.tagged_with(@filter, any: true)
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image_url, :category_id, :rating, :body, :tag_list, :interest_list, :image, :price, :address)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	# acts tag
	include ActsAsTaggableOn::TagsHelper
end

app/views/posts/_main.html.erb
<div class="col-lg-8 col-md-8">
          <div class="row ">            
            <div class="col-lg-12 rounded-lg" >
              
              
           
              <div class="">

                <div class="card" style="width: 100%; border-radius: 6px;">
                  <div class="card-header bg-transparent">
                    New post
                  </div>
                  <div class="card-body" style="padding: 0;">

                    <div class="media form-edit-user align-items-center">
                      <img class="m-3 avatar" src="" alt="Generic placeholder image">
                      <div class="media-body ">
                        
                        <p class="text-muted" style="font-size: 1.5em;" data-toggle="modal" data-target="#new_post_modal">What's happening? </p>
                        
                      </div>
                    </div>
                    
                  </div>
                </div>
              </div> <!-- end row card -->
              <div class="m-3">
                <% if @count %>  
                  <% if @count >0 %>
                  <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                  <strong>Nice!</strong> We found <%= @count %> results.
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  </div>
                  <% else %>

                  <button type="button" class="btn btn-warning mt-2 mb-2">
                    Result <span class="badge badge-light">0</span>
                  </button>
                  <% end %>
                <% end %>
              </div> <!-- end white -->

    
        <div class="bg-white" style=" border-radius: 6px;">
          <%# content_for :title, "What's do you wanna eat" %>
            <%# navigation_add 'Posts', posts_path %>
            <%#= render_navigation %>
          <div class=""> <!-- dang la p-3 -->



                
                


        

            <div class="rounded-lg bg-grey">


              <div class="sticky-top" style="background-color:  #e9ebee" >
                <div class="nav-scroller py-1 mb-2" style="border-radius: 6 6 0 0;">
                  <nav class="nav d-flex justify-content-between" id="ein-filter" style=" background-color: white; border-radius: 6px;">     
                    <a class="p-2 ml-3 grab ein-active" data-toggle="pill" href="#home">
                      <i class="far fa-fire-alt" style="font-size: 1.2rem;"></i>
                      Wishlist
                    </a>

                    <a class="p-2 grab" data-toggle="pill" href="#nearby">
                      <i class="fas fa-location" style="font-size: 1.2rem;"></i>
                      Nearby
                    </a>


                    <a class="p-2 grab" href="#">
                       Trending</a>
                    <a class="p-2 grab" href="#">Hightest rated</a>
                    <a class="p-2 grab" href="#">Suggestion</a>
                    <%= link_to "Lastest", recent_posts_path, class: "p-2 grab" %>
              
                  </nav>
                </div>
              </div>  
              <!-- Tab panes -->
              <div class="tab-content">
                <div class="tab-pane container active" id="home">
                  <div class="row">
                    <div id="posts">
                      <%= render @posts %>
                      <%#= render partial: "post", collection: @posts %>
                      <%#= render 'post', posts: @posts %>

                    </div>
                  </div>
                  <div class="apple_pagination">
                    <%#= will_paginate @posts %>
                  </div>
                </div>
                
                
                <div class="tab-pane container" id="menu1">
                  <div class="row">
                    <%#= render @all_posts %> 
                  </div>
                </div>
                  
                  
                <div class="tab-pane container" id="nearby">
                  <div class="row"> 
                    <%#= render @top5posts %>
                    
                    <% if @nearby_post %>
                      <%= render @nearby_post  %>
                    <% else %>
                      <%= link_to 'add my location', new_location_path %>
                    <% end %>
                 
                    <%#    Post.near([@lat, @long], 10).map do |post| %>
                      <%#= post.address %> <%#= post.distance.round(2) %>
                    <%# end %>

                  </div>  
                </div>
              </div>
            </div>   <!-- end white -->
          </div> <!-- end p-3 --> 
        </div>    <!-- end of row -->
        </div>   <!-- end col -lg-8 -->

            
            <div class="col-lg-12" style="background-color: #e9ebee">
              <div class="">
                
                <div class="input-group mb-2">
                  <div class="input-group-prepend">
                    <div class="input-group-text" style="border: none; background-color: white;  border-radius: 2rem 0 0 2rem; padding-left: 20px;">
                      <i class="far fa-search" style="font-size: 1.2rem;"></i>
                    </div>
                  </div>
                  <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Search chonmon" style="border: none; box-shadow:none !important; border-radius: 0 2rem 2rem 0;">
                </div>

                <div class="search-box"> 
    
                  <input placeholder="Search chonmon" type="text" class="form-control">  
                  
                </div>

                <div class="form-edit-user">
                    
                  <p>Bạn yêu thích cộng đồng chonmon và muốn nó trở nên lớn mạnh hơn?</p>
                  <a class="btn btn-sm btn-outline-secondary  badge-pill" href="#" role="button">Donate us</a>
                  <hr class="my-4">
                  <img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=60" class="img-fluid">
                </div>

              </div>
   

    
            </div>
            
          
        
    </div> <!-- end of row -->
  </div> <!-- end of container-fluid -->

app/views/posts/_post.html.erb
<div class="media border-bottom mb-3 pb-3">
  <img class="mr-3 img-fluid rounded align-self-center" src="<%= post.image_url %>" alt=" placeholder image" style="width: 120px; height: 120px;  object-fit: cover;">
  <div class="media-body">
    <h5 class="mt-0">
      <%= link_to post.title, post, class: "text-decoration-none",  data: {toggle: "modal", target: ".bd-example-modal-lg-#{post.id}"} %>

      <%= link_to edit_post_path(post) do %>
      <i class="fal fa-edit float-right text-muted" ></i>
      <% end %>

    </h5>
    <span class="small text-muted" style="font-weight: 600;"> <%#= (Time.now.to_date - post.created_at.to_date).to_i %>  
      <%= time_ago_in_words(post.created_at) %> ago >  <%= post.address %>
    </span>
     
    <% if post.nearbys(5, :units => :km)%>  
     Nearby 
      <% post.nearbys(5, :units => :km).map do |location| %>
       <%= link_to location.address, posts_path %>
      <% end %> 
    <% end %>   
    </p>
    
    <%= post.content %></br>
    <%= link_to post.interest_list, tagged_with_posts_path(post_tag: post.interest_list) %>
    
    <%# @tags.each do |tag| %>
                <%#= link_to "##{tag}", tag_path(:basic => "#{tag}") %>
              <%# end %>
    
      <% post.tags.each do |t| %>
        <span class="badge badge-secondary">#<%= t.name %></span>
        <span class="badge badge-secondary">#<%= link_to t.name, tagged_path(tag: t) %></span>

      <% end %>
    

    <span class="badge  badge-warning">Spacious</span>
    <span class="badge  badge-success">Pizza</span>

    <%  if post.hash_tags.exists? %>
      <% post.hash_tags.each do |hash_tag| %>
        <span class="badge  badge-success hash-tag-<%= hash_tag.id %>" onclick="clickfunc(this)"><%= hash_tag.name %></span>
        <script>
          if($(".hash-tag-<%= hash_tag.id %>:contains('ngon')").length > 0){
              $(".hash-tag-<%= hash_tag.id %>").css( "background", "#ffc107" );
          }
          if($(".hash-tag-<%= hash_tag.id %>:contains('khonganlai')").length > 0){
              $(".hash-tag-<%= hash_tag.id %>").css( "background", "#6c757d" );
          } 
          if($(".hash-tag-<%= hash_tag.id %>:contains('spacious')").length > 0){
              $(".hash-tag-<%= hash_tag.id %>").css( "background", "#ffc107" )
                                                .css("color", "#212529")
              ;
          } 


          function clickfunc(obj) {
              var t = $(obj).text();
              //alert(t);
              $("#home .media").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(t) > -1)
              });
          }

           
        </script>
      <% end %>
    <% end %>
    <span class="badge  badge-success">Ribs</span>
    
    
    <span class="stars-container stars-80">★★★★★</span>

    
    
  <% if current_user %>
    <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
    <% @like = current_user.likes.find_by(post_id: post.id) %>
    <div id="like-<%= post.id %>">
      <%= render partial: "likes/button", locals: {post: post} %>

    </div>
  <% end %>  
  </div>

        <%#= link_to 'Show', post, class: "btn btn-secondary" %></td>
        
</div>


<div class="modal fade bd-example-modal-lg-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl ">
    <div class="modal-content bg-transparent" style="border: none;">
      
      <div class="row no-gutters justify-content-center">
    
        <div class="col-lg-auto  align-self-center" >
          <img class="" src="<%= post.image_url %>" alt="<%= post.title %>" style="max-height: 600px; max-width: 600px; object-fit: cover; width: 100%;">

           <!--<img src="https://images.unsplash.com/photo-1562051725-cc35a65c8227?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" class="img-fluid dich-img" style="max-width: 500px;"> -->
          <!--<img src="https://images.unsplash.com/photo-1543362906-acfc16c67564?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" class="img-fluid dich-img" style="max-width: 500px; max-height:500px;">-->
        </div>
        <div class="col-lg-4 bg-white" >
          
          <div class="p-2 hid_scroll" style="max-height: 600px; overflow-y: scroll; ">
            <h5 class="mt-0 text-muted">
              <%= post.title %>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="fal fa-times-circle float-right" style="color: green; font-size:1.5rem;" ></i>
              </button>
              
              
             
            </h5>

            <%= post.content %>
            <%  if post.hash_tags.exists? %>
              <% post.hash_tags.each do |hash_tag| %>
                <span class="badge  badge-success hash-tag-<%= hash_tag.id %>"><%= hash_tag.name %></span>
              <% end %>
            <% end %>
            <span class="stars-container stars-90">★★★★★</span>
            

            <h5>comments</h5>
            <%= form_with(model: [post, post.comments.build]) do |f| %>
              <%= f.text_field :content, data: {postID: "#{post.id}"}, id: "#{post.id}" %>
              <%= f.submit "create", class: "comment-submit" %>
            <% end %>
                        
            <div id="msg-<%= post.id %>">
            </div>
            <div class="modal-footer">
              blah
            </div>

            


          </div>
          
        </div>
      </div> <!-- end of row -->
    <!-- end of container -->
    </div>
  </div>
</div>

app/views/posts/_sidebar.html.erb
<div class="col-lg-4 col-md-4">
          <div class="card mb-2" style="border-radius: 6px; background-color: #febb02;">
            <div class="card-body">
              <h5> pg Search </h5>
                <%= form_tag posts_path, class: "", remote: true, method: :get do %>
                  <div class="form-group">
                  <%= text_field_tag "pg_search", params[:pg_search], placeholder: "Enter dish's name ", class: "form-control" %>
                  </div>
                  <%= submit_tag "Search", class: "btn btn-primary" %>
                <% end %>

            </div>
          </div>

          <div class="card" style="border-radius: 6px; border-color: rgb(230, 236, 240);">
            <div class="card-header bg-transparent" style="color: #17bf63">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mr-1" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
              <strong>Search filter</strong>
            </div>
            <div class="card-body">
              

              <h5 class="card-title">Categories</h5>

              <%= form_tag posts_path, class: "form-check-test", method: :get, remote: true do %>
                <div class="custom-control custom-checkbox">
                  <%= check_box_tag 'category[]', "1", false, id: "customCheck4", class: "custom-control-input"  %>
                  <label class="custom-control-label" for="customCheck4">Food</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <%= check_box_tag 'category[]', "2", false, id: "customCheck5", class: "custom-control-input" %>
                  <label class="custom-control-label" for="customCheck5">Drink</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <%= check_box_tag 'category[]', "3", false, id: "customCheck6", class: "custom-control-input" %>
                  <label class="custom-control-label" for="customCheck6">Coffee</label>
                </div>
                <%#= submit_tag "Search", class: "btn btn-warning my-2 my-sm-0" %>
                <%= link_to "Reset", posts_path  %>  
              <% end %>

              <%= simple_form_for :filter, url: posts_path, class: "form-check-test2", method: :get, remote: true, defaults: { input_html: { class: 'custom-control-input' } } do |f| %>
                
                  <%= f.input :types, label: "Restaurant",  collection: $types, as: :check_boxes, item_label_class: 'custom-control-label', wrapper_html: { class: 'custom-checkbox' }  %>
                             
                  <%= f.input :interests, label: "Food interests",  collection: $interests, as: :check_boxes, item_label_class: 'custom-control-label', wrapper_html: { class: 'custom-checkbox' }  %>
                  <%= f.input :monan, label: "Kind",  collection: $monan, as: :check_boxes, item_label_class: 'custom-control-label', wrapper_html: { class: 'custom-checkbox' } %>
                <%= submit_tag "Search", class: "btn btn-warning my-2 my-sm-0" %>
                <%= link_to "Reset", posts_path  %>  
              <% end %>

              
              <h5 class="card-title mt-2">Location</h5>


              <div class="custom-control custom-radio">
                <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
                <label class="custom-control-label" for="customRadio1">Anywhere</label>
              </div>
              <div class="custom-control custom-radio">
                <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
                <label class="custom-control-label" for="customRadio2">Near you</label>
              </div>


              <form>
                <label for="customRange1" class="mt-2">Price range</label>
                <input type="range" class="custom-range" id="customRange1">

   
              </form>
              <h5> Popular Tags </h5>

              <%# @tags.each do |tag| %>
                <%#= link_to "##{tag}", tag_path(:basic => "#{tag}") %>
              <%# end %>

             
            </div>


            <div class="card-footer bg-transparent">Advance search</div>
          </div>



          <div class="mt-3">
            <h5 class="text-muted">
              <div class="">
                <a class="text-muted  " href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
                </a>
                Categories
              </div>
            </h5>
            


            <%#= form_tag posts_path, class: "form-inline my-2 my-lg-0 pb-2", method: :get do %>
              <%#= text_field_tag :d, params[:d], placeholder: "Gần đây", class: "form-control mr-sm-2" %>
              <%#= submit_tag "Search", class: "btn btn-warning my-2 my-sm-0" %>
            <%# end %>


            <%#= form_tag posts_path, class: "form-inline my-2 my-lg-0 pb-2", method: :get do %>
              <%#= text_field_tag :search, params[:search], placeholder: "Tìm kiếm", class: "form-control mr-sm-2" %>
              <%#= submit_tag "Search", class: "btn btn-warning my-2 my-sm-0" %>
            <%# end %>


  


            <div class="">
              <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">

                <a class="nav-link" id="v-pills-home-tab" data-toggle="pill" href="#top_choice" role="tab" aria-controls="v-pills-home" aria-selected="true">
                  <%= image_tag("icons/award", size: "20x20") + " Editor choice"  %>

                </a>
                <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#home" role="tab" aria-controls="v-pills-home" aria-selected="true">
                  <%= image_tag("icons/radar", size: "20x20") + " Nearby me"  %>
                  <i class="fal fa-coffee fa-fw" style="font-size:1rem;"></i> 
                </a>
                <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#menu2" role="tab" aria-controls="v-pills-profile" aria-selected="false">
                  <%= image_tag("icons/star", size: "20x20") + " Highest rating"  %>
                  </a>

                <a class="nav-link grab" id="v-pills-messages-tab" data-toggle="pill" href="#menu1" role="tab" aria-controls="v-pills-messages" aria-selected="false">
                  <%= image_tag("icons/fire", size: "20x20") + " Hot "  %>  
                </a>

              </div>
            </div> <!-- end white -->
          
          </div>
        </div>

app/views/posts/edit.html.erb
<div class="container">
	
    <div class="bg-white p-3 rounded-lg">
		<h3>Editing Post</h3>

		<%= render 'form', post: @post %>

		<%= link_to 'Show', @post %> |
		<%= link_to 'Back', posts_path %>
	</div>
	
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="bg-white p-3 rounded-lg">
      <h5><%= @post.title %></h5>
  


  <p>
    <strong>Content:</strong>
    <%= @post.content %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= @post.image_url %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @post.category_id %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= @post.rating %>
  </p>

    <%= @post.body %>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>

  </div>

  <h5>comments</h5>
  <%= form_with(model: [@post, @post.comments.build]) do |f| %>
    <%= f.text_field :content %>
    <%= f.submit "create", class: "comment-submit" %>
  <% end %>
              
  <div id="msg-<%= @post.id %>">
  </div>

  <% @post.comments.each do |comment| %>
    <%= comment.content %>
  <% end %>


</div>

<% if @post.image.attached? %>
<!-- @post.image.present? will always return true, use attached? to check presence -->
  <p>
    <strong>Image:</strong>
    <br>
    <%= image_tag @post.image.variant(resize: "500x500") %>
  </p>
<% end %>






<div id="like-<%= @post.id %>">

  <%= render partial: "likes/button", locals: {post: @post} %>

</div>