config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users
  

	  resources :posts do
	  	resources :comments
	  	resources :likes
      collection do
        get :recent
        get :tagged_with
      end
	  end


  resources :categories
  resources :users, only: [:show, :edit, :update] do
    resources :locations
  end
  get '/users/:user_id/locations/:id/sua_diadiem' => 'locations#sua_diadiem', as: :sua_diadiem
  get 'community', to: "users#community", as: :community
  
  get 'welcome/index'
  root 'welcome#index'

  get '/tagged', to: "posts#tagged", as: :tagged

  get '/search' => 'posts#search', :as => 'search_page'

#test
  get '/tag', to: "posts#click_tag", as: :tag


  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :user
	#belongs_to :post

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  validates_presence_of :address

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :sua_diadiem]
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    #@locations = @current_user.locations
  end

  # GET /locations/1
  # GET /locations/1.json
  def show

  end

  # GET /locations/new
  def new
    #@location = Location.new
    @location = current_user.locations.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    #@location = Location.new(location_params)
    @location = current_user.locations.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sua_diadiem
    @location = current_user.locations.last
      
      respond_to do |format|
        format.html { }#redirect_to request.referer || root_path }
        format.js {}
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end



end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_sua_diadiem.html.erb
<div class="container">

	<%= form_for([@location.user, @location]) do |f| %>


	      <div class="field">
	        <%#= f.label 'current address:' %>
	        <%#= f.text_field :address, data: {location_ID: "#{@address.id}"}, class: "styling_formholder form-control" %> 

	        <%= f.text_field :address, data: {location_ID: "#{@location.id}"}, class: "styling_formholder form-control" %>
	      </div>

	
		    <%= f.submit f.object.new_record? ? "New message" : "Update", class: "btn btn-primary" %>


	<% end %>
</div>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/locations/sua_diadiem.js.erb
$('.pet-show').html("<%= j render partial: 'locations/sua_diadiem' %>");

var geocoder = new google.maps.Geocoder();

navigator.geolocation.getCurrentPosition(function(location) { 
	lat = location.coords.latitude; 
	lng = location.coords.longitude; 
	var latlng = new google.maps.LatLng(lat, lng);

    geocoder.geocode({'latLng': latlng}, function(results) {
      var yourLocation = results[0].formatted_address ;
      console.log(yourLocation);

		$("input[data-location-id=<%= @location.id %>]").val(results[0].formatted_address);
		
 
    });

});


	$('#reload-button').click();