config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users
  

	  resources :posts do
	  	resources :comments
	  	resources :likes
      collection do
        get :recent
        get :tagged_with
      end
	  end


  resources :categories
  resources :users, only: [:show, :edit, :update] do
    resources :locations
  end
  get '/users/:user_id/locations/:id/sua_diadiem' => 'locations#sua_diadiem', as: :sua_diadiem
  get 'community', to: "users#community", as: :community
  
  get 'welcome/index'
  root 'welcome#index'

  get '/tagged', to: "posts#tagged", as: :tagged

  get '/search' => 'posts#search', :as => 'search_page'

#test
  get '/tag', to: "posts#click_tag", as: :tag


  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apptest66</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/eebc152b5c.js" crossorigin="anonymous" data-mutate-approach="sync"></script>
    <%= favicon_link_tag asset_path("icons/papaya") %>
    <%= stylesheet_pack_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQ538qNHtZiC1LCoGx1J6mUcUbPSlL5uM&libraries=places" ></script>
  </head>

  <body style="background-color: #e9ebee">
    

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #fff">
      
        <%= link_to image_tag("icons/papaya", size: "30x30") + " food insider", posts_path, class: "navbar-brand"  %>

      <div class="d-flex  align-items-center">
        
        <%= link_to 'New Post', new_post_path, class: "btn btn-outline-success" %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
      
            
       

          <li class="nav-item active ">           
            
            <a class="nav-link" href="#">
              <i class="fal fa-user fa-fw" style="font-size:1rem;"></i>
              Sign in <span class="sr-only">(current)</span>
            </a>

           
            
           
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="#">
              <i class="fal fa-coffee fa-fw" style="font-size:1rem;"></i> 
              Blog
            </a>
          </li>

          <li class="nav-item ">

            <a class="nav-link" href="#">
              <i class="fal fa-envelope fa-fw" aria-hidden="true" style="font-size:1rem;"></i> Notification
            </a>

          </li>
          <li class="nav-item ">

            <input class="form-control" id="myInput" type="text" placeholder="Search">

            

          </li>
          
            
         
        </ul>
      </div>

      
    </nav>

         <% if user_signed_in? %>       
         <div class="btn-group">
              <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user"></i>
                <%= current_user.email %>
                <%= current_user.id %>
              </button>
                <div class="dropdown-menu">
                  <%= link_to current_user.user_name, user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Change password", edit_user_registration_path, class: "dropdown-item" %>

                  <%#= link_to "Room I followed", myrooms_path, class: "dropdown-item" %>
                  <%#= link_to 'My locations', user_locations_path(@current_user), class: "dropdown-item" %>
                  <div class="dropdown-divider">
                  
                  </div>
                    <%= link_to "Sign out", destroy_user_session_path, method: "delete", class: "dropdown-item" %>
                  </div>
            </div>
        <% else %>
                    <%= link_to image_tag("icons/user", size: "20x20") + " Sign in", new_user_session_path, class: "nav-link" %>
        <% end %> 
        
        <% if current_user && current_user.locations.exists? %>
          <%= current_user.locations.last.address %>
        <% end %>
  
<!--
    <div class="jumbotron jumbotron-fluid" style="background-image: url('https://images.unsplash.com/photo-1483664852095-d6cc6870702d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80'); object-fit: cover; background-repeat: no-repeat; background-size: 100%; background-position: center center;">
      <div class="container">
        <h3 class="display-4" style="color: white">Finest food</h3>
        <p class="lead" style="color: white">occupies the entire horizontal space of its parent</p>
      </div>
    </div>
  -->


  <%# flash.each do |name, msg| %>
    <%#= content_tag :div, msg, id: "flash_#{name}" %>
  <%# end %>


  <%= yield %>

  </body>
</html>